"""curve_fx_harness_client package."""

from .client import EvaluatorClient
from .exceptions import (
    AttestationError,
    EvaluatorProcessError,
    HarnessError,
    IdentityMismatchError,
    ProtocolViolationError,
    RemoteEvaluatorError,
    SessionError,
)
from .hashing import sha256_file
from .models import (
    ArtifactRef,
    BatchResultFrame,
    CandidateResult,
    CandidateSpec,
    CloseSessionFrame,
    ErrorFrame,
    EvaluateBatchFrame,
    EvaluatorIdentity,
    HelloFrame,
    Limits,
    MetricProjection,
    ObservationKind,
    ObservationSpec,
    OpenSessionFrame,
    ScenarioInfo,
    ScenarioResult,
    SessionClosedFrame,
    SessionReadyFrame,
    ShutdownFrame,
)

__all__ = [
    "EvaluatorClient",
    "HelloFrame",
    "EvaluatorIdentity",
    "Limits",
    "OpenSessionFrame",
    "SessionReadyFrame",
    "EvaluateBatchFrame",
    "BatchResultFrame",
    "CandidateSpec",
    "CandidateResult",
    "ScenarioResult",
    "ObservationSpec",
    "ObservationKind",
    "MetricProjection",
    "ArtifactRef",
    "ErrorFrame",
    "CloseSessionFrame",
    "SessionClosedFrame",
    "ShutdownFrame",
    "ScenarioInfo",
    "HarnessError",
    "ProtocolViolationError",
    "EvaluatorProcessError",
    "IdentityMismatchError",
    "AttestationError",
    "SessionError",
    "RemoteEvaluatorError",
    "sha256_file",
]
